sudo: false
language: c
compiler:
    - gcc
os:
    - linux
script:
    - sh -x ./install.sh -p $HOME/install_test/ --with-ethernet --with-fortran=false
after_failure:
    - cat ./install.log
after_script:
    - cat ./install.log
after_success:
    - cd $HOME/install_test/tests/
    - echo $HOSTNAME > machines
    - echo $HOSTNAME >> machines
    - sh -x ./runtests.sh
    - cd -
    - bash <(curl -s https://codecov.io/bash)
